adding instance_format to variable query
nasa/python_cmr pull request #60
Opened 2024-06-10 15:50 UTC by briannapagan

Following the conversation here: https://github.com/nasa/python_cmr/issues/59 
NASA GES DISC is releasing public zarr stores for specific variables of collections. The only way to discover what available zarr stores at variable level is via the CMR parameter `instance_format`. This simple PR adds this as a search parameter in `VariablesQuery`.

2024-06-10 16:02 UTC, sliu008 commented on cmr/queries.py
> +            return self
probably be better to do this instead
if instance format:
  self.params['instance_format'] = instance_format
 
 return self

2024-06-10 16:17 UTC, chuckwondo requested changes

2024-06-10 16:17 UTC, chuckwondo commented on tests/test_variable.py
> +    def test_archive_center(self):
```suggestion
    def test_instance_format(self):
```

2024-06-10 16:17 UTC, chuckwondo commented on cmr/queries.py
> +            return self
agreed, it's a minor difference, but slightly preferred

2024-07-08 16:04 UTC, frankinspace commented
Also please add an entry to the changelog

2024-07-08 22:14 UTC, chuckwondo commented
@briannapagan, do you have time to address the change requests and add the appropriate changelog entry, so we can get this into the next release?

2024-08-19 17:50 UTC, chuckwondo commented
@briannapagan, are you able to address the changes requested on the PR, including adding a changelog entry? There have been a few other PRs merged into the develop branch since you opened this one, so you'll have to get your branch up to date with the develop branch as well.

2024-09-03 17:15 UTC, closed without merging