Added support for multiple-point searches
nasa/python_cmr pull request #73
Opened 2024-08-13 17:26 UTC by Sherwin-14

I came up with a naive solution for the issue #72

2024-08-13 17:47 UTC, frankinspace requested changes
Can you add a unit test for this one?

2024-08-13 18:07 UTC, chuckwondo requested changes
In addition to my code comments, I will repeat @frankinspace's request for you to also include unit tests, which should generally be done as a matter of practice.

2024-08-13 18:07 UTC, chuckwondo commented on cmr/queries.py
> +        return self
@Sherwin-14, as we discussed in the [related earthaccess issue](https://github.com/nsidc/earthaccess/issues/491#issuecomment-2282799680), we do not want to add a new method. Rather, we want to modify the existing `point` method such that it _adds_ a point each time it is called, rather than setting a single point.

2024-08-13 18:07 UTC, chuckwondo commented on cmr/queries.py
> +
@Sherwin-14, there should be no need to modify this method. As mentioned in [the related earthaccess issue](https://github.com/nsidc/earthaccess/issues/491#issuecomment-2282801846), we simply need to modify the existing `point` method to keep track of _multiple_ points, rather than only 1 point, so we should be able to modify `point` similar to how `revision_date` keeps track of multiple values. See <https://github.com/nasa/python_cmr/blob/develop/cmr/queries.py#L396>.

2024-08-14 17:21 UTC, chuckwondo requested changes
Thanks @Sherwin-14. Looks good. Just 1 request for slight change to the changelog entry.

2024-08-14 17:21 UTC, chuckwondo commented on CHANGELOG.md
> +- Support for multiple-point searches ([#72](https://github.com/nasa/python_cmr/issues/72))
```suggestion
### Added

- Support multi-point searches ([#72](https://github.com/nasa/python_cmr/issues/72))
```

2024-08-14 18:13 UTC, chuckwondo commented
@Sherwin-14, looks like there's another unit test that needs to be adjusted to pass, like the change made to `test_point_set`.

2024-08-15 17:56 UTC, chuckwondo approved these changes

2024-08-17 21:14 UTC, chuckwondo commented
@frankinspace, are you ready to approve the changes now?

2024-08-19 16:04 UTC, frankinspace approved these changes
Looks good. Thank you!

2024-08-19 16:04 UTC, merged