Enable STAC Output for GranuleQuery
nasa/python_cmr pull request #82
Opened 2024-08-29 18:16 UTC by scottyhq

Address #81 

Basic usage:
```python
api = GranuleQuery() 
search = api.parameters(
    point=(-105.78, 35.79),
    temporal=('2021-02-01','2021-03-01'),
    collection_concept_id='C2021957657-LPCLOUD'  # collection_concept_id required for STAC search
)
items = search.format("stac").get()
```

2024-08-29 20:30 UTC, chuckwondo requested changes
@scottyhq, thanks for your submission! Please see my comments, and please also add an entry to `CHANGELOG.md`.

2024-08-29 20:30 UTC, chuckwondo commented on tests/test_granule.py
> +
@scottyhq, we use vcrpy for recording http requests so that we don't make live calls during unit testing. Since this method is within the `TestGranuleClass` class, running the unit tests locally should generate the file `tests/fixtures/vcr_cassettes/TestGranuleClass.test_stac_output.yaml`. Did you run the unit tests, and did that file get generated? If so, please also commit that file. If not, please let us know if you have any trouble doing so.

2024-08-29 20:30 UTC, chuckwondo commented on cmr/queries.py
> +
I'm getting nit-picky here, but please remove the added trailing whitespace from this line, as well as from the 2 other spots in this file.

2024-08-30 05:51 UTC, scottyhq commented on tests/test_granule.py
> +
I've never heard of vcrpy seems like an interesting approach! I did run the tests but missed committing this file. Hopefully it works!

2024-08-30 05:51 UTC, scottyhq commented on cmr/queries.py
> +
Yeah, I was just using a simple editor in jupyterhub. I resaved with 'trim trailing whitespace' in vscode, hopefully that works

2024-08-30 12:17 UTC, chuckwondo approved these changes
Great! Thank you!

2024-08-30 12:25 UTC, merged