updated adding instance_format to variable query
nasa/python_cmr pull request #83
Opened 2024-09-03 17:19 UTC by briannapagan

Following the conversation here: https://github.com/nasa/python_cmr/issues/59
NASA GES DISC is releasing public zarr stores for specific variables of collections. The only way to discover what available zarr stores at variable level is via the CMR parameter instance_format. This simple PR adds this as a search parameter in VariablesQuery.

Closed last PR as it fell behind other commits: https://github.com/nasa/python_cmr/pull/60 

Should encompass all feedback

2024-09-03 21:42 UTC, chuckwondo requested changes
Hi @briannapagan. Thanks for opening this new PR. I made suggestions for supporting multiple instance format values, as allowed by the CMR.

2024-09-03 21:42 UTC, chuckwondo commented on tests/test_variable.py
> +        self.assertEqual(query.params["instance_format"], "zarr")
```suggestion
    def test_instance_format(self):
        query = VariableQuery()
        query.instance_format("zarr")

        self.assertIn("instance_format", query.params)
        self.assertEqual(query.params["instance_format"], ["zarr"])

    def test_instance_formats(self):
        query = VariableQuery()
        query.instance_format(["zarr", "kerchunk"])

        self.assertIn("instance_format", query.params)
        self.assertEqual(query.params["instance_format"], ["zarr", "kerchunk"])
```

2024-09-03 21:42 UTC, chuckwondo commented on CHANGELOG.md
> +- Support `instance-format` to `VariableQuery` to allow for searching of variable zarr stores ([#59]https://github.com/nasa/python_cmr/issues/59)
```suggestion
- Support searching by instance format for `VariableQuery` ([#59]https://github.com/nasa/python_cmr/issues/59)
```

2024-09-04 16:37 UTC, frankinspace approved these changes

2024-09-04 18:48 UTC, briannapagan commented
Changed thank you @chuckwondo !

2024-09-04 20:40 UTC, chuckwondo approved these changes
Thanks @briannapagan (and @frankinspace)!

2024-09-05 17:45 UTC, merged